# Generated by Django 2.0 on 2017-12-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u24', '0004_advert_response_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='response_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ответ сервера'),
        ),
    ]
