# Generated by Django 2.0 on 2017-12-13 09:09

from django.db import migrations
import u24.models


class Migration(migrations.Migration):

    dependencies = [
        ('u24', '0005_auto_20171211_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='num',
            field=u24.models.NonStrippingCharField(help_text='обязтельно без 8', max_length=10, verbose_name='номер'),
        ),
    ]
