# Generated by Django 2.0 on 2018-07-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u24', '0008_mailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='from_email',
            field=models.CharField(default='', max_length=128, verbose_name='адрес'),
            preserve_default=False,
        ),
    ]
