# Generated by Django 2.0 on 2019-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u24', '0009_mailbox_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=models.TextField(max_length=350, verbose_name='текст'),
        ),
    ]
